### ISSUE TITLE
shape = Bemis-Murcko scaffold

### ISSUE THREAD

**Issue by UnixJunkie** [ghiander/novana#1]
in the literature, that's the name...

**Comment by ghiander** [comment]
Hello Francois,

Thanks for opening the issue. It is a good reminder for me to write a section about distinguishing Novana decompositions from Bemis-Murcko scaffolds. There is a discussion on going with regard to this point on my LinkedIn: https://www.linkedin.com/posts/ghiandonigianmarco_github-ghiandernovana-novana-novelty-activity-7098703222680219648-sZts?utm_source=share&utm_medium=member_desktop

The take home is that Novana scaffold/shapes and Bemis-Murcko scaffolds are slightly different:

![image](https://github.com/ghiander/novana/assets/30413455/5c69aac2-998c-4775-b631-bc2e8e2707ec)

**Comment by UnixJunkie** [comment]
I guarantee you that what you call "Shape" is the Bemis-Murcko scaffold. Rdkit implementation of BM scaffolds is not faithful; I once posted a correct implementation on the rdkit mailing list.

**Comment by ghiander** [comment]
Hello Francois, 

Thanks for pointing that out. I had a browse and I found that libraries implement different methods which they refer to as Bemis-Murcko scaffold decomposition - and also the literature refers to them using different definitions. But from their original publication, it looks like they're referring to their scaffold (framework) as a generic graph similar to what Novana shape is.

I'd be happy to point that out in my repository's documentation. I'm planning to introduce some new options to retain different levels of information in the shape generation as well.
